#!/usr/bin/env python
import sys
import xlrd
def add(a, b):
  return a+b

def production():
  data = xlrd.open_workbook('demo.xls')
  data.sheet_names()
  table = data.sheets()[0]
  for rownum in range(table.nrows):
    for colnum in range(table.ncols):
      print str(able.cell(rownum, colnum).value)
    print '\n'
