# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contest_submit.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contest_submit.proto',
  package='contest_submit',
  serialized_pb='\n\x14\x63ontest_submit.proto\x12\x0e\x63ontest_submit\".\n\rContestSubmit\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x11\n\ttimestamp\x18\x02 \x02(\x03')




_CONTESTSUBMIT = _descriptor.Descriptor(
  name='ContestSubmit',
  full_name='contest_submit.ContestSubmit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='contest_submit.ContestSubmit.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='contest_submit.ContestSubmit.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['ContestSubmit'] = _CONTESTSUBMIT

class ContestSubmit(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTESTSUBMIT

  # @@protoc_insertion_point(class_scope:contest_submit.ContestSubmit)


# @@protoc_insertion_point(module_scope)
