# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='contestant_ac.proto',
  package='contestant_ac',
  serialized_pb='\n\x13\x63ontestant_ac.proto\x12\rcontestant_ac\"U\n\x0c\x43ontestantac\x12\n\n\x02id\x18\x01 \x02(\x05\x12\n\n\x02\x61\x63\x18\x02 \x02(\x08\x12\x0e\n\x06submit\x18\x03 \x02(\x05\x12\x0c\n\x04time\x18\x04 \x02(\x05\x12\x0f\n\x07penalty\x18\x05 \x02(\x05')




_CONTESTANTAC = descriptor.Descriptor(
  name='Contestantac',
  full_name='contestant_ac.Contestantac',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='contestant_ac.Contestantac.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ac', full_name='contestant_ac.Contestantac.ac', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='submit', full_name='contestant_ac.Contestantac.submit', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time', full_name='contestant_ac.Contestantac.time', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='penalty', full_name='contestant_ac.Contestantac.penalty', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['Contestantac'] = _CONTESTANTAC

class Contestantac(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTESTANTAC
  
  # @@protoc_insertion_point(class_scope:contestant_ac.Contestantac)

# @@protoc_insertion_point(module_scope)
